name: canable_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line  
  provider: ^5.0.0
  connectivity: ^3.0.3
  bloc: ^7.0.0
  google_fonts: ^2.0.0

  cupertino_icons: ^1.0.0




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^2.0.5
  google_sign_in: ^5.0.1
  flutter_downloader: ^1.5.0
  http: ^0.13.1
  firebase_core_platform_interface: ^4.0.0
  flare_flutter: ^3.0.0
  flutter_bloc: ^7.0.0   #helps in implementing blocs
  equatable: ^2.0.0 #helps in comparing class using their values
  firebase_storage: ^8.0.3
  lite_rolling_switch: ^0.1.1
  time_formatter: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  firebase_auth: ^1.0.3
  random_string: ^2.1.0
  cupertino_tabbar: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_signin_button: ^1.0.0
  firebase_messaging: ^10.0.2
  image_picker: ^0.8.1+1
  change_app_package_name: ^1.0.0
  cloud_firestore: ^2.2.2
  sign_button: ^2.0.0
  wechat_camera_picker: ^2.1.1
  cached_network_image: ^3.0.0
  share: ^2.0.1
  flutter_screenutil: ^5.0.0
  firebase_core: ^1.0.3
  animated_bottom_navigation_bar: ^0.3.2
  flutter_awesome_buttons: ^0.1.0
  flutter_auth_buttons: ^0.10.0
  flutter_icons: ^1.1.0
  firebase_auth_web: ^1.0.5
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  line_awesome_icons: ^1.0.4+2
  file_picker: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logocanable.png"   

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/noi.png
    - assets/canable.JPG
    - assets/Canable.png
    - assets/A1.png
    - lib/lang/en.json
    - lib/lang/ur.json
    - lib/lang/hi.json
    - assets/A2.png
    - assets/A3.png
    - assets/A4.png
    - assets/COD.png
    - assets/QC.png
    - assets/DT.png
    - assets/referralImage.png
    - assets/shirtC.png
    - assets/pantC.png
    - assets/kurtaPajamaC.png
    - assets/alter.png
    
    - assets/alter1.png
    - assets/alter2.png
    # - assets/salwarSuit.png
    - assets/12.png
    - assets/blouse.png
    - assets/lehengaimage.png
    - assets/gararaImage.png
    # - assets/patchesSuitCard.png
    # - assets/patchesSuitCard1.png
    # - assets/patchesSuitCard2.png
    # - assets/pak.png
    - assets/ringSS.png
    - assets/Group 17.png
    # - assets/sendYourDesign.flr
    - assets/shavez1.flr
    - assets/ani1.flr
    # - assets/sendYourDesign1.flr
    # - assets/sendYourDesign2.flr
    # - assets/pakistaniSuit.flr
    # - assets/pakistaniSuit1.flr
    # - assets/pakistaniSuit2.flr
    - assets/stack.png
    - assets/adjust.png
    - assets/Success Check.flr
    - assets/referralCodeImage.png
    # - assets/homeSPen.png
    # - assets/homeSPhi.png
    # - assets/homeSPur.png
    - assets/logo3.jpg
    # - assets/editingpageaudio.mp3
    - assets/start.flr
    # - assets/lehengaaudio.mp3
    # - assets/summaryaudio.mp3
    # - assets/editaudio.mp3
    # - assets/infoaudio.mp3
    # - assets/measureaudio.mp3
    # - assets/designSound.mp3
    - assets/suitImage.png
    - assets/frockImage.png
    # - assets/noMeasurement.png
    # - assets/noMeasurement1.png
    - assets/redhead.png
    # - assets/noMeasurement2.png
    # - assets/measurementCard.png
    # - assets/measurementCard1.png
    # - assets/measurementCard2.png
    - assets/measurementCloth.png
    - assets/measurementCloth1.png
    - assets/measurementCloth2.png
    # - assets/salwarSuitCard.png
    # - assets/salwarSuitCard1.png
    # - assets/salwarSuitCard2.png
    - assets/freeImage.png
    - assets/hanger.png
    # - assets/homeSP.png
    - assets/topSS.png
    - assets/bottomSS1.png
    - assets/play.flr
    - assets/uploadFabric.png
    # - assets/sendYourDesignCard.png
    # - assets/sendYourDesignCard1.png
    # - assets/sendYourDesignCard2.png
    - assets/uploadFabric2.png
    - assets/homeImage.png
    - assets/homeImage2.png
    - assets/uploadFabric.png
    - assets/uploadFabric1.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  fonts:
    - family: CodeProlight
      fonts:
        - asset: assets/CodeProLowercase.ttf
    - family: CodePro
      fonts:
        - asset: assets/CodeProLowercaseBold.ttf
    - family: Graphik
      fonts:
        - asset: assets/Graphik-Regular.ttf
    - family: Helvetica
      fonts:
        - asset: assets/Helvetica.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/MyFlutterApp.ttf    
    - family: Helvetica_rounded
      fonts:
        - asset: assets/helvetica-rounded-bold.otf
    - family: Graphik_super
      fonts:
        - asset: assets/Graphik-Super.ttf    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
